---
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: Replace origin of devel/pkg-config with devel/pkgconfig
    script: roles/common/files/set_pkg_config_origin.sh
    args:
      creates: /etc/pkg/updated_pkg_config_origin

  - name: Install essential dependencies
    pkgng:
      name: "{{item}}"
      state: present
    with_items:
    - curl
    - postgresql96-server-9.6.8_1
    - git
    - blas
    - lapack
    - gsl
    - devel/pkgconf
    # needed for unarchive command, boo
    - gtar
    # haskell stack dependencies
    - devel/gmake
    - perl5
    - lang/gcc
    - misc/compat8x
    - misc/compat9x
    - converters/libiconv
    - ca_root_nss

  - name: Download haskell stack
    get_url:
      url: https://www.stackage.org/stack/freebsd-x86_64
      dest: /var/tmp/stack-1.6.5-freebsd-x86_64.tar.gz

  - name: Extract haskell stack 
    unarchive:
      src: /var/tmp/stack-1.6.5-freebsd-x86_64.tar.gz
      dest: /var/tmp/stack-1.6.5-freebsd-x86_64

  - name: Copy stack to /usr/local/bin
    copy:
      src: /var/tmp/stack-1.6.5-freebsd-x86_64/stack
      dest: /usr/local/bin/stack-1.6.5-freebsd-x86_64
      mode: u=rx,g=rx,o=rx

  - name: Symlink stack-1.6.5 to stack
    file:
      src: /usr/local/bin/stack-1.6.5-freebsd-x86_64
      dest: /usr/local/bin/stack
      state: link
      mode: u=rwx,g=rx,o=rx
    
## fix gcc
#mv /lib/libgcc_s.so.1 /lib/libgcc_s.so.1.bad
#ln -s /usr/local/lib/gcc6/libgcc_s.so.1 /lib/libgcc_s.so.1
