---
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: Replace origin of devel/pkg-config with devel/pkgconfig
    command: pkg set -o devel/pkg-config:devel/pkgconfig
    args:
      creates: /etc/pkg/updated_pkg_config_origin
  - name: Mark that pkg-config was updated
    copy:
      content: '# Created by anisble run'
      dest: /etc/pkg/updated_pkg_config_origin

  - name: Install essential dependencies
    pkgng:
      name: "{{item}}"
      state: present
    with_items:
    - curl
    - postgresql96-server-9.6.8_1
    # git is for development purposes only
    - git
    - blas
    - lapack
    - gsl
    - devel/pkgconf
    # needed for unarchive command, boo
    - gtar
    # haskell stack dependencies
    - devel/gmake
    - perl5
    - lang/gcc
    - misc/compat8x
    - misc/compat9x
    - converters/libiconv
    - ca_root_nss
    # Development tools
    - neovim

  - name: Download haskell stack
    get_url:
      url: https://github.com/commercialhaskell/stack/releases/download/v1.6.5/stack-1.6.5-freebsd-x86_64.tar.gz
      dest: /var/tmp/stack-1.6.5-freebsd-x86_64.tar.gz

  - name: Extract haskell stack 
    unarchive:
      src: /var/tmp/stack-1.6.5-freebsd-x86_64.tar.gz
      dest: /var/tmp/

  - name: Copy stack to /usr/local/bin
    copy:
      src: /var/tmp/stack-1.6.5-freebsd-x86_64/stack
      dest: /usr/local/bin/stack-1.6.5-freebsd-x86_64
      mode: u=rx,g=rx,o=rx

  - name: Symlink stack-1.6.5 to stack
    file:
      src: /usr/local/bin/stack-1.6.5-freebsd-x86_64
      dest: /usr/local/bin/stack
      state: link
      mode: u=rwx,g=rx,o=rx

  - name: Create /usr/local/etc/libmap.d directory
    file:
      path: /usr/local/etc/libmap.d
      state: directory
  - name: libmap configuration for libgcc6
    copy:
      src: roles/common/files/libgcc6.conf
      dest: /usr/local/etc/libmap.d/libgcc6.conf

  - name: Set vagrant user shell to sh
    user:
      name: vagrant
      shell: /bin/sh
      groups: vagrant

  - name: Copy id_rsa for using github
    copy:
      src: roles/common/files/id_rsa
      dest: /home/vagrant/.ssh/id_rsa
      owner: vagrant
      group: vagrant
      mode: u=rw,g-rwx,o-rwx

  - name: create home aws dir
    file:
      path: /home/vagrant/.aws
      state: directory
  - name: Copy aws config file
    copy:
      src: roles/common/files/config
      dest: /home/vagrant/.aws/config
  - name: Copy aws credentials file
    copy:
      src: roles/common/files/credentials
      dest: /home/vagrant/.aws/credentials

  - name: create /home/vagrant/.local/bin for yesod devel
    file:
      path: /home/vagrant/.local/bin
      state: directory

  - name: Set environment variables for development
    blockinfile:
      path: /home/vagrant/.profile
      block: |
         PATH=$PATH:/home/vagrant/.local/bin; export PATH
         PGHOST=10.0.2.2; export PGHOST
         DERPWATCH_MODE=readonly; export DERPWATCH_MODE
